image: python:latest
stages:
    - setup-stage
    - test
    - build-stage
    - deploy-feature-stage
    - deploy-stage
    - deploy-server-stage
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  FF_USE_FASTZIP: "true"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  IMAGE_TAG: obasi79/sbj-webapp
  DOCKER_IMAGE_TAG: obasi79/sbj-webapp:$CI_COMMIT_SHORT_SHA
  # DOCKER_IMAGE_TAG: obasi79/sbj-webapp:$CI_COMMIT_REF_SLUG

  GITLAB_IMAGE_TAG: $CI_REGISTRY_IMAGE/sbj-webapp/app-image:$CI_COMMIT_REF_SLUG


  FEATURE_APP: $IMAGE_TAG/$CI_ENVIRONMENT_SLUG
  PRIVATE_SERVER: "https://198.211.29.93"
  STAGING_APP: sbjwebapp-staging
  PRODUCTION_APP: sbjwebapp-production

  APEXBUGSERVER_STAGING: obasi79/$STAGING_APP:$CI_COMMIT_REF_SLUG
  APEXBUGSERVER_PRODUCTION: obasi79/$PRODUCTION_APP

cache:
  untracked: true
  policy: push
  key: ${CI_COMMIT_SHORT_SHA}
  paths:
    - .cache/pip
    - venv/
    - pytest_reports/









setup:
  stage: setup-stage
  image: python:latest
  tags:
    - sbjwebapp
  before_script:
    - source venv/bin/activate
    - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - echo $FEATURE_APP
    - pip3 install -r requirements.txt