version: '3.4'

services:
  sbj-webapp:
    image: sovereignblkv2
    stdin_open: true # docker run -i
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
