version: '3.4'

services:
  sbjwebapp:
    image: obasi79/sbjwebapp-production
    stdin_open: true
    tty: true

    build:
        context: .
        dockerfile: ./Dockerfile
    environment:
        NODE_ENV: development
    ports:
        - 3700:80
