"""empty message

Revision ID: 155ecbf80c52
Revises: 4b0b5ff2d9d8
Create Date: 2023-01-02 06:24:23.122114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155ecbf80c52'
down_revision = '4b0b5ff2d9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playershands',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('hand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'hand_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playershands')
    # ### end Alembic commands ###
