"""empty message

Revision ID: 4b0b5ff2d9d8
Revises: dbe55de4d129
Create Date: 2023-01-02 06:22:04.271697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b0b5ff2d9d8'
down_revision = 'dbe55de4d129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('player_limit', sa.Integer(), nullable=False),
    sa.Column('h_value', sa.Integer(), nullable=False),
    sa.Column('l_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hands')
    # ### end Alembic commands ###
