"""empty message

Revision ID: 36dbe92d6d23
Revises: 
Create Date: 2023-01-02 05:50:34.106262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36dbe92d6d23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('h_value', sa.Integer(), nullable=False),
    sa.Column('l_value', sa.Integer(), nullable=False),
    sa.Column('face', sa.String(length=3), nullable=True),
    sa.Column('suite', sa.String(length=8), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('face')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
