"""empty message

Revision ID: dc35c370d73c
Revises: 8bd2fbc40090
Create Date: 2023-01-02 06:51:35.189477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc35c370d73c'
down_revision = '8bd2fbc40090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pot', sa.Integer(), nullable=False),
    sa.Column('player', sa.Integer(), nullable=False),
    sa.Column('dealer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
