"""empty message

Revision ID: 300313d436af
Revises: 36dbe92d6d23
Create Date: 2023-01-02 05:54:00.473787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300313d436af'
down_revision = '36dbe92d6d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    # ### end Alembic commands ###
