version: '3.4'

services:
  flasksbj:
    image: flasksbj
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3400:8080

    environment:
      - FLASK_APP =sbj/wsgi.py

  # pg:
  #     container_name: pg_container2
  #     image: postgres:13.2-alpine
  #     restart: always
  #     environment:
  #         POSTGRES_USER: postgres
  #         POSTGRES_PASSWORD: pass123
  #         POSTGRES_DB: sbj
  #         POSTGRES_HOST_AUTH_METHOD: trust
  #     ports:
  #         - "5432:5432"


  # pgadmin:
  #     container_name: pgadmin_container2
  #     image: dpage/pgadmin4:5.2
  #     restart: always
  #     environment:
  #         PGADMIN_DEFAULT_EMAIL: admin@example.com
  #         PGADMIN_DEFAULT_PASSWORD: admin123
  #         PGADMIN_LISTEN_PORT: 5433
  #         PGADMIN_CONFIG_SERVER_MODE: "False"
  #         PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
  #     ports:
  #         - "5433:5433"
  #     depends_on:
  #         - pg