version: '3.4'

services:
  flasksbj:
    image: flasksbj
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 6000 5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_APP =sbj/wsgi.py

