version: '3.4'

services:
  flasksbj:
    image: flasksbj
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8080

    environment:
      - FLASK_APP =sbj/wsgi.py

