"""empty message

Revision ID: e15d9ab13556
Revises: d3374462ee04
Create Date: 2022-12-12 23:38:09.729525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15d9ab13556'
down_revision = 'd3374462ee04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('h_value', sa.Integer(), nullable=False),
    sa.Column('l_value', sa.Integer(), nullable=False),
    sa.Column('face', sa.String(length=3), nullable=True),
    sa.Column('suite', sa.String(length=8), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('face')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
