"""empty message

Revision ID: 012ef43f808a
Revises: e15d9ab13556
Create Date: 2022-12-12 23:57:12.665041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012ef43f808a'
down_revision = 'e15d9ab13556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deckcards',
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('deck_id', 'card_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deckcards')
    # ### end Alembic commands ###
