"""empty message

Revision ID: f7ae12cdde94
Revises: 
Create Date: 2022-12-13 00:33:45.222480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ae12cdde94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deckcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used', sa.Boolean(), nullable=True))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_status', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('finished_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('finished_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('game_status')

    with op.batch_alter_table('deckcards', schema=None) as batch_op:
        batch_op.drop_column('used')

    # ### end Alembic commands ###
