"""empty message

Revision ID: 08397f461104
Revises: f5dc10332981
Create Date: 2022-12-13 23:49:50.078086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08397f461104'
down_revision = 'f5dc10332981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    # ### end Alembic commands ###
