"""empty message

Revision ID: 20803f25edd0
Revises: a2fd1c21a421
Create Date: 2022-12-14 04:19:04.596950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20803f25edd0'
down_revision = 'a2fd1c21a421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
