name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    environment: DEVELOPMENT
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check Variables
      # 1. $AZURE_REGISTRY_NAME   3. ${AZURE_REGISTRY_NAME}
      run:    echo "2. ${{AZURE_REGISTRY_NAME}}"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sbj21registry.azurecr.io/sbj-webapp:v1
    - name: docker login
      run: $AZURE_REGISTRY_PASS | docker login -u $AZURE_REGISTRY_NAME $AZURE_REGISTRY_SERVER
    - name: Push image
      run: docker push sbj21registry.azurecr.io/sbj-webapp:v1
    - name: Job Complete
      run : echo "Docker build and Push complete"

