name: Docker Image CI
env:
   USERNAME: ${{vars.AZURE_REGISTRY_NAME}}
   SERVER: ${{vars.AZURE_REGISTRY_SERVER}}
   PASS: ${{vars.AZURE_REGISTRY_PASS}}
   IMAGE: ${{SERVER}}/sbj-webapp:v1
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    environment: DEVELOPMENT
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check Variables
      run:    echo 2. ${{SERVER}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE
    - name: docker login
      run: $PASS | docker login -u $USERNAME $SERVER
    - name: Push image
      run: docker push $IMAGE
    - name: Job Complete
      run : echo "Docker build and Push complete"

